### ISSUE TITLE
Automatic PRs for version 0.3.6.2, 0.3.6.3, 0.3.6.4?

### ISSUE THREAD

**Issue by LaurentRDC** [conda-forge/pandoc-crossref-feedstock#20]
Hello,

I'm looking to update to pandoc-crossref 0.3.6.4 (released yesterday) and I noticed that this repo has not received any PR from regro-cf-autotick-bot. What's going on?

**Comment by kiwi0fruit** [comment]
I have no idea how to make regro-cf-autotick-bot work. GitHub repo has files with very unconvenient names so bot is not able to use them automatically. I'd prefer that it would still make a broken PR but apparently it doesn't work this way.

**Comment by kiwi0fruit** [comment]
Or may be I don't see a way to rewrite the script for bot to update them automatically.

**Comment by LaurentRDC** [comment]
Fair enough! Just thought I would ask.
