### ISSUE TITLE
maintenance help

### ISSUE THREAD

**Issue by knaaptime** [conda-forge/pandoc-crossref-feedstock#36]
Hi @kiwi0fruit just wanted to say thanks again for putting this recipe together! I use the conda-packaged version of pandoc-crossref in all my [academic workflows](https://github.com/knaaptime/mandown) to make the analysis and paper fully reproducible, so just wanted to offer my willingness to help you maintain this recipe if you'd like.

**Comment by mfansler** [comment]
bump

**Comment by mfansler** [comment]
Hi @knaaptime. I hopped in to get the latest version merged, but I'm just a Conda Forge generalist, so it'd be great to have a heavy user join the effort. At the moment, I'm touching up the 0.3.10.0 build, but after that I'd suggest that you resubmit (e.g., rebase) your previous PR and include yourself as a maintainer in the recipe.

I'll let you know once I've finished the 0.3.10.0 rebuild.

**Comment by knaaptime** [comment]
awesome, thank you @mfansler. That PR was a [postrelease fix](https://github.com/lierdakil/pandoc-crossref/issues/289) for 0.3.9, so with 0.3.10 merged we can probably just close it. I can open a new one adding myself as a maintainer?

**Comment by mfansler** [comment]
Yes, that makes sense.
