### ISSUE TITLE
Bump upper bound on Pandoc

### ISSUE THREAD

**Issue by LaurentRDC** [conda-forge/pandoc-crossref-feedstock#39]
Hello,

The latest version of pandoc-crossref [supports pandoc 2.12](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.10.0) explicitly, but I see that the current conda-force package does not. Would it be possible to bump the pandoc upper bound to 2.13?

Thanks!

**Comment by mfansler** [comment]
Yes, sorry about that. I overlooked it when I first pushed 0.3.10.0, but have fixed it with PR https://github.com/conda-forge/pandoc-crossref-feedstock/pull/37. Please let me know if there is still an issue. (Note the new build hasn't deploy to Anaconda Cloud yet.)
